server:
  port: 10086
spring:
  application:
    name: eurekaserver  # eureka的服务名称
  cloud:
    nacos:
      server-addr: 8848
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka